### ISSUE TITLE
How to obtain Blogspot's country-specific domain (ccTLD) list.

### ISSUE THREAD

**Issue by cokebar** [cokebar/gfwlist2dnsmasq#1]
Google search uses ccTLDs, like google.com.hk/google.co.jp. And the whole list can be found here:
https://www.google.com/supported_domains

For blogspot, it has same situation. But I don't know how to obtain the whole domain list.

Anyone can help?

**Comment by wyf88** [comment]
I don't think an official list exists, but it seems someone has tested.
http://bloggerdomainextensions.blogspot.com/2016/11/bloggerdomainextensions.html

**Comment by cokebar** [comment]
@wyf88 Thanks for the information. I'll deal with it soon.

**Comment by cokebar** [comment]
Closed by 94f9ad8
