### ISSUE TITLE
Use short option for base64 for compatibility of Busybox base64

### ISSUE THREAD

**Issue by wyf88** [cokebar/gfwlist2dnsmasq#11]
```
if [ $SYS_KERNEL = "Darwin"  -o $SYS_KERNEL = "FreeBSD" ]; then
    BASE64_ERES='base64 -D'
else
    BASE64_ERES='base64 -d'
fi
```
This way the script can be embedded in OpenWrt/Lede for updating GFWList regularly.

**Comment by cokebar** [comment]
I've tested on OpenWrt 15.05.1/14.07 and LEDE, seeing that busybox-base64 is not included.
In order to use base64 in OpenWrt/LEDE, GNU-coretils-base64 should be installed, which supports `--decode`.

**Comment by wyf88** [comment]
Yes, `base64` is not included by default in OpenWrt's version of Busybox. But it can be enabled when compiling OpenWrt with the following config:
```
CONFIG_BUSYBOX_CONFIG_BASE64=y
```
And this simplified version of `base64` supports short option only. I'm thinking that... it does not hurt to consider the compatibility with it :)

**Comment by cokebar** [comment]
2f264fb
