### ISSUE TITLE
Doesn't work on BSD based system

### ISSUE THREAD

**Issue by szkane** [cokebar/gfwlist2dnsmasq#2]
./gfwlist2dnsmasq.sh -f ~/Desktop/1.txt
./gfwlist2dnsmasq.sh: line 106: md5sum: command not found
-e Fetching GfwList...base64: invalid option -- d
Usage:	base64 [-hvD] [-b num] [-i in_file] [-o out_file]
  -h, --help     display this message
  -D, --decode   decodes input
  -b, --break    break encoded string into num character lines
  -i, --input    input file (default: "-" for stdin)
  -o, --output   output file (default: "-" for stdout)
-e  Done.

Converting GfwList to dnsmasq rules...
-e
WARNING:
The following lines in GfwList contain regex, and might be ignored.

-e
This script will try to convert some of the regex rules. But you should know this may not be a equivalent conversion.
If there's regex rules which this script do not deal with, you should add the domain manually to the list.

sed: illegal option -- r
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
sed: illegal option -- r
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
sed: illegal option -- r
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
-e Fetching Google search domain list...-e  Done

Google search domains... Added.
Blogspot domains... Added.
twimg.edgesuit.net... Added.
Ipset rules not included.
-e
Converting GfwList to dnsmasq rules... Done.

-e Generating dnsmasq configuration file...-e  Done.

-e Cleaning up...-e  Done.

Finished!

**Comment by cokebar** [comment]
Try e90d540

**Comment by cokebar** [comment]
What is your OS?

**Comment by cokebar** [comment]
If your system is a BSD based system, this script may not compatible to you.
I'll try to support BSD later.

**Comment by szkane** [comment]
MAC OS10

**Comment by cokebar** [comment]
@szkane Please try #3

**Comment by cokebar** [comment]
fixed through #3
