### ISSUE TITLE
代码健壮性问题

### ISSUE THREAD

**Issue by Alion548** [cokebar/gfwlist2dnsmasq#29]
https://github.com/cokebar/gfwlist2dnsmasq/blob/00e2200b16233bf97eb35106aa00fc5d84572087/gfwlist2dnsmasq.sh#L75

当缺少which 命令时，脚本执行出现异常。

**Comment by cokebar** [comment]
Comment out Line 314 to bypass the dependency check
https://github.com/cokebar/gfwlist2dnsmasq/blob/master/gfwlist2dnsmasq.sh#L314
