### ISSUE TITLE
openwrt_shadowsocks 环境下，telegram客户端 无法联网

### ISSUE THREAD

**Issue by Ausua** [cokebar/gfwlist2dnsmasq#39]
openwrt_shadowsocks 环境下，安卓手机版telegram 无法联网，我使用如下教程搞定的，除了telegram客户端（win10 版和安卓版，linux未试）不能联网，其它一切正常。

**Comment by Ausua** [comment]
设置telegram代理 192.168.1.1:1081，问题解决，OK

**Comment by cokebar** [comment]
This issue is not related to this repo. 
gfwlist2dnsmasq ONLY DO CONVERTION WORK FROM GFWLIST TO DNSMASQ RULES.
ALL OTHER THINGS, LIKE PROXY, TUNNEL IS NOT RELATED TO THIS REPO.

Please do not publish this kind of issue any more.

**Comment by cokebar** [comment]
This issue will be deleted in 8 hours.
