### ISSUE TITLE
Doesn't work on entware-arm@Asuswrt-merlin

### ISSUE THREAD

**Issue by qw918** [cokebar/gfwlist2dnsmasq#4]
gfwlist2dnsmasq.sh -f /jffs/configs/dnsmasq.d/dnsmasq_gfw.conf

/jffs/scripts/gfwlist2dnsmasq.sh: line 50: getopts: not found
Please enter full path to the file.( Use: -f /path/to/output_filename)

**Comment by cokebar** [comment]
I have never used merlin, and know none about it. Could you please give me some documents for reference?

**Comment by cokebar** [comment]
Please try 5cf9fcc
This script needs curl, sed, awk, base64. I'm not sure if they're included in merlin. But just have a try.

**Comment by cokebar** [comment]
closed due to inacitivity
