### ISSUE TITLE
Is it possible to add nftable sets support?

### ISSUE THREAD

**Issue by zcy85611** [cokebar/gfwlist2dnsmasq#45]
dnsmasq 2.87 would be able to add nftable sets, Is it possible to add nftable sets support?

**Comment by ravenchan** [comment]
Already tried & working so far, here's what I use for now :
nftset=/dns.google/ip#table#set
Change "ip" to "ip6" for  ipv6 addresses.
Change "table" to your own table name,and "set" to your own set name.
