### ISSUE TITLE
Ability to customize (include/exclude) domains

### ISSUE THREAD

**Issue by wyf88** [cokebar/gfwlist2dnsmasq#6]
It will be helpful to be able to add extra domains that are not in the output. Maybe they are in the original gfwlist in a regex form and not transformed in the output dnsmasq config. Or maybe they are blocked or very slow to visit from a specific ISP.

Similarly, it is also helpful to be able to remove domains from the gfwlist.

**Comment by cokebar** [comment]
I'll do it later.

**Comment by cokebar** [comment]
Include extra domains: 400d7df
exclude domains: planning to do

**Comment by ericwang2006** [comment]
有一个极路由的域名hiwifi.com, 不知道为什么进入了gfwlist, 我估计是数据问题,   确实是需要一个include/exclude的列表,还请大神有空处理一下
--

**Comment by cokebar** [comment]
@wyf88 @ericwang2006 for exclude domain file, please try 0b5a510 ("exclude-domain-file" branch).
If there's no critical bugs, I'll merge the branch to the master.

**Comment by cokebar** [comment]
#19 merged.
closed.
